# Minimal configuration for RadSec over Tailscale
# Binding to 127.0.0.1 prevents address conflict.

listen {
    type = auth
    ipaddr = 127.0.0.1
    port = 2083
}

listen {
    type = acct
    ipaddr = 127.0.0.1
    port = 2083
}
