# /radius-server/radiusd.conf
listen {
    type = auth
    ipaddr = *
    port = 2083
    proto = tcp
    tls = yes
    
    # Path to the certs managed by Certbot
    certdir = /etc/letsencrypt/live/${RADIUS_DOMAIN}/
    ca_file = ${certdir}/chain.pem
    private_key_file = ${certdir}/privkey.pem
    certificate_file = ${certdir}/fullchain.pem
}
